ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS role TEXT;

UPDATE public.questions SET role = CASE sector
  WHEN 'it' THEN 'Software Engineer'
  WHEN 'software' THEN 'Software Engineer'
  WHEN 'civil-services' THEN 'Civil Services (IAS/IPS)'
  WHEN 'government' THEN 'Government Officer'
  WHEN 'banking' THEN 'Bank PO / Officer'
  WHEN 'teaching' THEN 'School Teacher'
  WHEN 'sales' THEN 'Sales Executive'
  WHEN 'healthcare' THEN 'Staff Nurse'
  ELSE 'Any role'
END WHERE role IS NULL;

INSERT INTO public.questions (sector, role, category, difficulty, prompt, tip, ideal_answer) VALUES
('software','Frontend Engineer','technical','easy','What is the difference between the DOM and the virtual DOM, and why does React use one?','Talk about reconciliation cost, not just "it is faster".','The DOM is the browser''s live tree of nodes; mutating it triggers style, layout and paint. React keeps a lightweight JS description of the UI (the virtual DOM), diffs the new tree against the previous one and applies the minimal set of real DOM mutations in a batch. The win is not raw speed but a declarative model: you describe state, React figures out the minimum mutation. Mention keys, reconciliation heuristics, and that a hand-tuned direct DOM update can still beat React.'),
('software','Frontend Engineer','technical','medium','A page scores poorly on Largest Contentful Paint. Walk me through how you would diagnose and fix it.','Name the metric targets and the tools you would open first.','Reproduce with Lighthouse and a throttled WebPageTest run, then read the LCP element and its subparts: TTFB, resource load delay, load time, render delay. Common fixes: serve the hero from a CDN with modern formats and correct sizes, preload it, remove render-blocking CSS/JS, inline critical CSS, use fetchpriority="high", avoid lazy-loading the hero, and cut server latency with caching or SSR streaming. Verify with field data (CrUX/RUM), aiming for LCP under 2.5s at p75.'),
('software','Frontend Engineer','technical','hard','How would you architect state in a large React app with server data, URL state and local UI state?','Separate the three kinds of state explicitly.','Split by ownership: server cache state belongs in a data layer such as TanStack Query with query keys, staleness and invalidation; URL state (filters, pagination, selected id) belongs in the router so it is shareable and back-button safe; ephemeral UI state stays in local component state or a small store. Avoid duplicating server data into a global store. Discuss normalisation only when entities are shared, optimistic updates with rollback, and how you keep derived state computed rather than stored.'),
('software','Backend Engineer','technical','medium','How do you make a payment API endpoint idempotent?','Idempotency key plus a uniqueness constraint in the database.','Require the client to send an Idempotency-Key header. On receipt, insert the key into a table with a unique constraint inside the same transaction as the charge; if the insert conflicts, return the stored response for that key instead of charging again. Store the request fingerprint to reject key reuse with a different payload, give keys a TTL, and make downstream calls to the processor with the same key so retries collapse there too. Mention at-least-once delivery and why exactly-once is a client+server contract.'),
('software','Backend Engineer','technical','hard','A background job queue is backing up and latency is climbing. How do you respond?','Stabilise first, then find the cause.','First stabilise: check consumer health and error rate, scale consumers if CPU-bound, and shed or defer low-priority job types so critical work drains. Then diagnose: is it a poison message retry loop, a slow downstream dependency, a lock contention hotspot, or genuine volume growth? Look at per-job-type latency, retry counts and DB wait events. Fixes range from batching and connection pooling to moving to a dead-letter queue with capped retries and backoff. Close with a durable fix plus alerting on queue depth and oldest-message age.'),
('software','Data Engineer','technical','medium','Explain the difference between a batch ETL pipeline and a streaming pipeline, and when you would choose each.','Tie the answer to freshness requirements and cost.','Batch processes bounded chunks on a schedule; it is simpler, cheaper, easy to backfill and reprocess, and fine when consumers tolerate hours of latency. Streaming processes unbounded events with windowing and watermarks; it delivers second-level freshness but adds state management, out-of-order handling and operational complexity. Choose by SLA: dashboards refreshed daily stay batch; fraud detection or live inventory needs streaming. Mention the lambda/kappa trade-off and that many teams run micro-batches as a pragmatic middle ground.'),
('it','Data Analyst','technical','medium','Given a SQL table of orders, how would you find the monthly retention rate of new customers?','Describe the cohort logic before writing syntax.','Define a cohort as customers by first purchase month. Compute first_order_month per customer with MIN(order_date) grouped by customer, join it back to orders, then count distinct customers active in each subsequent month offset. Retention for month N is active customers in cohort month + N divided by cohort size. Mention using DATE_TRUNC, a calendar table to keep zero months visible, and being explicit about whether "active" means any order or a qualifying order.'),
('it','Data Analyst','behavioral','medium','Tell me about a time your analysis contradicted what a stakeholder believed. What happened?','Show how you validated before you challenged.','Use STAR. Situation: a stakeholder was confident about a driver of churn. Task: validate before presenting. Action: re-checked data quality, ran a sanity segment cut, sought a second source, then presented the finding with the method and its limits, framed as a question rather than a correction. Result: quantified decision change. Emphasise that you led with evidence and gave them a path to act, not a verdict.'),
('it','DevOps Engineer','technical','medium','What is your rollback strategy when a deploy goes bad at 2am?','Fast, boring and rehearsed beats clever.','Prefer immutable, versioned artifacts so rollback is redeploying the last known-good image. Use progressive delivery: canary or blue-green with automated health gates so most bad deploys never reach full traffic. Keep database migrations backward compatible (expand-migrate-contract) so code rollback does not require schema rollback. Have a documented runbook, a single command, and alerting tied to SLOs. Afterwards, blameless postmortem and a test that would have caught it.'),
('it','QA Engineer','technical','easy','How do you decide what to automate and what to test manually?','Cost of the test versus cost of the bug escaping.','Automate the stable, high-value, repetitive paths: unit tests for logic, API tests for contracts, a thin layer of end-to-end tests for critical user journeys (login, checkout). Keep exploratory, usability and one-off checks manual. Avoid automating flaky UI details or features still churning. Frame it as the test pyramid plus risk: frequency of execution multiplied by the business cost of failure, against maintenance cost.'),
('software','Product Manager','behavioral','medium','How do you decide what not to build?','Show an explicit prioritisation frame and a real trade-off.','Start from the outcome metric and the constraint, not the feature list. Score candidates on reach, impact, confidence and effort, then check strategic fit and opportunity cost. Say no by making the trade-off visible: what we would delay, what evidence would change the answer. Give a concrete example including the stakeholder conversation and how you kept the relationship while holding the line. Mention writing the decision down so it does not get re-litigated monthly.'),
('software','Product Manager','technical','medium','Our activation rate dropped 12% week over week. How do you investigate?','Segment before theorising.','Confirm the metric is real: check instrumentation, a deploy or tracking change, and whether the drop is one segment or all. Cut by platform, geography, acquisition channel, new versus returning and app version. Look at the funnel step where the drop happens, then correlate with releases, experiments, pricing or an outage. Form a hypothesis, validate with a targeted query or session replay, and only then propose a fix with an expected recovery number.'),
('sales','Account Executive','behavioral','medium','Walk me through your last lost deal and what you would do differently.','Own the loss, show a system change.','Name the deal, the value, and where it died. Typical honest answer: single-threaded with a champion who left, or discovery that never surfaced the economic buyer''s metric. Explain the diagnosis: reviewed call notes, saw no mutual action plan and no quantified business case. What changed: multi-threading by the second call, a written mutual close plan, and a value hypothesis validated with the buyer. Close with the measurable effect on later deals.'),
('sales','Sales Development Rep','behavioral','easy','You have 60 seconds on a cold call. What do you say?','Permission, relevance, one question, one ask.','Open with a pattern interrupt and permission: name, company, "I know I''m an interruption, can I take 30 seconds?" Then one line of relevance tied to their role or a trigger event, not your feature list. Ask one diagnostic question that earns the right to continue. End with a low-friction ask for a 15-minute call with a specific time. Emphasise tone, pausing, and that the goal is a next step, not a pitch.'),
('general','Marketing Manager','technical','medium','How would you measure whether a brand campaign worked?','Distinguish brand from performance measurement.','Brand campaigns rarely map to last-click. Set the objective first (awareness, consideration, preference), then use a matched-market or geo holdout test as the cleanest read, supported by brand lift surveys, branded search volume, direct traffic and assisted conversions over a longer window. Agree the measurement plan and the baseline before launch, state the expected effect size, and be explicit about what would count as a failure.'),
('general','HR / People Partner','behavioral','medium','A manager wants to fire someone after one bad quarter. How do you handle it?','Protect the process and the business.','Slow the decision without dismissing the concern. Gather specifics: were expectations documented, was feedback given, are there context factors (scope change, personal circumstances, a bad manager fit)? Coach the manager into a clear, time-bound performance plan with written expectations and support. Check legal and policy exposure and consistency with how others were treated. If performance genuinely does not move, execute the exit respectfully and quickly. Show you serve the business and fairness at once.'),
('healthcare','Staff Nurse','interview','medium','A doctor prescribes a dose you believe is unsafe. What do you do?','Patient safety, escalate through the chain, document.','Do not administer. Verify the order and the patient''s weight, allergies and renal function against the reference range. Raise it directly and respectfully with the prescriber, stating the specific concern and the reference. If unresolved, escalate to the charge nurse, then the on-call senior or pharmacist per policy. Document the concern, the conversation and the outcome. Frame it as a normal safety practice, not a conflict.'),
('healthcare','Medical Lab Technician','technical','medium','How do you handle a lab result that is critically abnormal?','Verify, notify, document, within the turnaround policy.','Check for pre-analytical error: sample integrity, haemolysis, labelling, and repeat or rerun with a control if indicated. If confirmed, follow the critical-value policy: notify the responsible clinician within the defined window, use read-back confirmation, and document the time, person notified and result. Flag repeated analyser drift for QC review.'),
('banking','Bank PO / Officer','technical','medium','A long-standing customer asks you to approve a loan slightly outside policy. How do you respond?','Empathy plus a firm line, and a real alternative.','Acknowledge the relationship and explain the specific policy constraint and why it exists (credit risk, regulatory exposure, fairness to other customers). Do not commit informally. Offer legitimate alternatives: restructure the amount or tenure, add collateral or a co-applicant, or escalate for a documented, sanctioned exception through the credit committee. Document the request and the decision.'),
('banking','Credit Analyst','technical','hard','Which three ratios do you look at first when assessing an SME loan, and why?','Pick ratios and explain what a bad number would tell you.','Leverage (debt/EBITDA) to size the burden against cash generation; interest coverage (EBIT/interest) for the ability to service in a rate shock; and the current ratio or working-capital cycle for near-term liquidity, since SMEs fail on cash, not profit. Add why the numbers can lie: related-party revenue, seasonality, promoter funding treated as equity. Conclude with the cash-flow projection and covenant structure you would set.'),
('government','Government Officer','interview','hard','You discover a colleague has been accepting small gifts from a vendor. What do you do?','Rules first, but show judgement and process.','Establish the facts before acting: what was received, from whom, and whether it breaches the conduct rules and the procurement policy. Small or not, gifts from an active vendor create a conflict and must be reported through the prescribed channel, not handled informally. Speak to the colleague only if policy allows, report to the designated authority, avoid speculation with peers, and protect the procurement record. Emphasise consistency and confidentiality.'),
('civil-services','Civil Services (IAS/IPS)','interview','hard','As a district magistrate, communal tension is rising after a rumour spreads on social media. What are your first six hours?','Sequence: information, order, communication, legal.','Hour one: verify facts through police, local intelligence and field officers; convene the district crisis group. Establish order: preventive deployment at flashpoints, proportionate restrictions on assembly, and lawful detention of instigators. Counter the rumour: an official statement, engagement with community and religious leaders, and coordination with platforms and local media. Keep essential services and hospitals ready. Document every order. Follow with peace committees and a rehabilitation plan; avoid blanket internet shutdowns unless narrowly justified.'),
('teaching','School Teacher','interview','medium','A student''s performance drops suddenly. How do you respond?','Care first, evidence second, escalate appropriately.','Look for a pattern across subjects and attendance before concluding. Speak to the student privately and without judgement; possible causes range from home circumstances and health to bullying or a learning gap that has just become visible. Coordinate with the class teacher and counsellor, contact parents with observations rather than accusations, and put a small, specific support plan in place with a review date. Follow the safeguarding policy if anything indicates harm.'),
('general','Any role','behavioral','medium','Describe a time you received harsh feedback. What did you do with it?','Avoid a humblebrag; show the actual change.','Pick a real, specific piece of feedback with a sting. Explain your first reaction honestly, how you checked whether it was true (asked for examples, sought a second view), the concrete behaviour you changed and how you measured that it stuck. Close with what you now do differently by default. Interviewers reward self-awareness and evidence of change, not a flawless story.'),
('general','Any role','hr','medium','What is your salary expectation?','Anchor with a researched range and stay collaborative.','Ask for the budgeted range first if you can. If pressed, give a researched range for the role, level and location, state that it is based on market data and your current package, and say you are looking at the total offer including equity, bonus and growth. Never give a single number you would not accept, and avoid disclosing your current salary where you are not required to.');